### PR TITLE
Change to main, add setup for page body. Check in file comments for w…

### PR DESCRIPTION
**Pull request by JuBruce**
…here to add code

### CODE REVIEW

**Comment by tadowdy** [comment]
@JuBruce question: why did you change the navigation bar to only show the description under the icon when selected? I think that adds some ambiguity over what the icons represent.

**Comment by cliffordt1996** [comment]
> @JuBruce question: why did you change the navigation bar to only show the description under the icon when selected? I think that adds some ambiguity over what the icons represent.

I think the _button-zoom-effect_ looks good. It makes it clear which tab they are currently viewing.

**Comment by tadowdy** [comment]
I agree that I like it aesthetically; however, i think it could be a little ambiguous. Our icons I don't think represent what they're for enough. I'd say we can give the two options for the client and see which she likes better?

**Comment by tadowdy** [comment]
approving to get the structure for now. However, i'm going to create an issue for reverting the navigation bar.

**Pull request merged**
